# frozen_string_literal: true

require_relative "instruction_set"

module AmeEncoding
  # Deterministic projections of the shared InstructionSet IR.
  class InstructionEncodingRenderer
    ATTRIBUTE_BEGIN = "// BEGIN GENERATED AME ENCODING ATTRIBUTES"
    ATTRIBUTE_END = "// END GENERATED AME ENCODING ATTRIBUTES"
    TABLE_BEGIN = "// BEGIN GENERATED AME ENCODING ALLOCATION TABLE"
    TABLE_END = "// END GENERATED AME ENCODING ALLOCATION TABLE"

    ATTRIBUTE_BLOCK_PATTERN = /^#{Regexp.escape(ATTRIBUTE_BEGIN)}\n.*?^#{Regexp.escape(ATTRIBUTE_END)}$/m
    ALLOCATION_TABLE_PATTERN = /^#{Regexp.escape(TABLE_BEGIN)}\n.*?^#{Regexp.escape(TABLE_END)}$/m

    attr_reader :instruction_set

    def initialize(instruction_set)
      @instruction_set = instruction_set
    end

    def check!
      stale = []
      markdown_path = File.join(@instruction_set.root, "INSTRUCTION_ENCODINGS.md")
      allocation_path = File.join(@instruction_set.root, "src", "instruction-encoding-allocations.adoc")
      stale << "INSTRUCTION_ENCODINGS.md" unless File.file?(markdown_path) && File.read(markdown_path) == markdown

      allocation_source = File.read(allocation_path)
      attributes_current = region_current?(allocation_source, ATTRIBUTE_BLOCK_PATTERN,
                                           ATTRIBUTE_BEGIN, ATTRIBUTE_END, attribute_block)
      table_current = region_current?(allocation_source, ALLOCATION_TABLE_PATTERN,
                                      TABLE_BEGIN, TABLE_END, allocation_table)
      unless attributes_current && table_current
        stale << "src/instruction-encoding-allocations.adoc generated registry"
      end

      return if stale.empty?

      raise ValidationError,
            "stale generated encoding artifacts: #{stale.join(', ')}; " \
            "run ruby scripts/generate-instruction-encoding-table.rb"
    end

    def write!
      markdown_path = File.join(@instruction_set.root, "INSTRUCTION_ENCODINGS.md")
      allocation_path = File.join(@instruction_set.root, "src", "instruction-encoding-allocations.adoc")
      allocation_source = File.read(allocation_path)
      unless unique_region?(allocation_source, ATTRIBUTE_BLOCK_PATTERN, ATTRIBUTE_BEGIN, ATTRIBUTE_END) &&
             unique_region?(allocation_source, ALLOCATION_TABLE_PATTERN, TABLE_BEGIN, TABLE_END)
        raise ValidationError, "cannot find managed allocation registry in #{allocation_path}"
      end

      File.write(markdown_path, markdown)
      generated_allocation = allocation_source.sub(ATTRIBUTE_BLOCK_PATTERN, attribute_block)
                                              .sub(ALLOCATION_TABLE_PATTERN, allocation_table)
      File.write(allocation_path, generated_allocation)
    end

    def attribute_block
      lines = [ATTRIBUTE_BEGIN]
      @instruction_set.attribute_text.each do |name, value|
        lines << ":#{name}: #{value}"
      end
      lines << ATTRIBUTE_END
      lines.join("\n")
    end

    def markdown
      lines = []
      lines << "# AME instruction encoding table"
      lines << ""
      lines << "> Generated by `ruby scripts/generate-instruction-encoding-table.rb` from " \
               "`src/instructions.adoc` and `scripts/data/instruction-encoding-allocation.json`. " \
               "Do not edit manually."
      lines << ""
      lines << "The canonical decoder test is `(instruction_word & mask) == match`. " \
               "Fixed fields are listed from most-significant to least-significant bits."
      lines << ""
      lines << "## Collision audit"
      lines << ""
      lines << "| Check | Count |"
      lines << "|---|---:|"
      lines << "| Instructions | #{@instruction_set.entries.length} |"
      @instruction_set.format_counts.sort.each do |format, count|
        lines << "| #{format} encodings | #{count} |"
      end
      exact, partial = @instruction_set.overlaps.partition do |left, right|
        left[:mask] == right[:mask] && left[:value] == right[:value]
      end
      lines << "| Exact duplicate decode patterns | #{exact.length} |"
      lines << "| Partial decode-space overlaps | #{partial.length} |"
      lines << ""
      lines << "## Format allocation policy"
      lines << ""
      lines << "Every encoding retains `funct7[31:25]`, `funct3[14:12]`, and " \
               "`opcode[6:0]`. R2 converts only `src2[24:20]` to `xfunct5`; R1 also " \
               "converts `src1[19:15]`, yielding `xfunct10`. All instructions use " \
               "`funct3=000`. A fixed no-operand instruction may occupy a selector " \
               "reserved by its bank only when its remaining fields are fully fixed."
      lines << ""
      lines << allocation_summary
      lines << ""
      lines << "## All instruction encodings"
      lines << ""
      lines << "| # | Format | Instruction | Mnemonic | Operand fields | Function/fixed fields | Mask | Match |"
      lines << "|---:|---|---|---|---|---|---|---|"

      @instruction_set.entries.each_with_index do |entry, index|
        operands = entry[:fields].select { |field| field[:kind] == :operand }
                                 .sort_by { |field| -field[:hi] }
                                 .map { |field| "`#{field[:name]}[#{bit_range(field)}]`" }
                                 .join("; ")
        fixed = entry[:fields].select { |field| field[:kind] == :fixed }
                              .sort_by { |field| -field[:hi] }
                              .map { |field| render_fixed_field(field) }
                              .join("; ")
        lines << format(
          "| %d | %s | `%s` | `%s` | %s | %s | `0x%08x` | `0x%08x` |",
          index + 1,
          entry[:format],
          escape(entry[:name]),
          escape(entry[:mnemonic]),
          operands,
          fixed,
          entry[:mask],
          entry[:value]
        )
      end

      "#{lines.join("\n")}\n"
    end

    def allocation_table
      lines = []
      lines << TABLE_BEGIN
      lines << '[cols="1,1,1,2,2",options="header"]'
      lines << "|==="
      lines << "| Allocation | Instruction count | `funct7` allocation | Selector / fixed fields | Remaining capacity"
      lines << ""

      r3_used = @instruction_set.entries.select { |entry| entry[:format] == "R3" }
      allocated = hex_runs(@instruction_set.r3_allocated_funct7, 2)
      reserved = hex_runs(@instruction_set.r3_reserved_funct7, 2)
      r3_allocation = allocated
      r3_allocation += " except #{reserved}" unless reserved.empty?
      lines << "| R3 | #{r3_used.length} | #{r3_allocation} | n/a | " \
               "0 free; #{plural(@instruction_set.r3_reserved_funct7.length, 'reserved value')}"

      @instruction_set.banks.each do |bank|
        ordinary = @instruction_set.used_selectors(bank)
        fixed = @instruction_set.bank_fixed_entries(bank)
        selector_width = [(bank[:selector_bits] + 3) / 4, 1].max
        selector_parts = []
        selector_parts << "`#{bank[:selector_name]}=#{hex_runs(ordinary, selector_width, code: false)}`" unless ordinary.empty?
        unless fixed.empty?
          fixed.each do |entry|
            member = @instruction_set.fixed_members.find { |candidate| candidate[:name] == entry[:name] }
            selector_parts << "`0x#{hex(member[:selector], selector_width)}` fixes `#{entry[:name]}`"
          end
        end
        unused_reserved = bank[:reserved_selectors] - @instruction_set.fixed_members
                                                            .select { |member| member[:bank] == bank[:id] }
                                                            .map { |member| member[:selector] }
        unless unused_reserved.empty?
          selector_parts << "#{hex_runs(unused_reserved, selector_width)} reserved"
        end
        count = @instruction_set.bank_entries(bank).length + fixed.length
        remaining = @instruction_set.free_selectors(bank).length
        lines << "| #{bank[:label]} | #{count} | `{#{bank[:funct7_attribute]}}` | " \
                 "#{selector_parts.join('; ')} | #{remaining}"
      end

      free = @instruction_set.free_funct7
      lines << "| Unallocated | 0 | #{hex_runs(free, 2)} | n/a | " \
               "#{plural(free.length, '`funct7` bank')}"
      lines << "|==="
      lines << TABLE_END
      lines.join("\n")
    end

    private

    def unique_region?(source, pattern, begin_marker, end_marker)
      lines = source.lines.map(&:chomp)
      lines.count(begin_marker) == 1 && lines.count(end_marker) == 1 && source.scan(pattern).length == 1
    end

    def region_current?(source, pattern, begin_marker, end_marker, expected)
      unique_region?(source, pattern, begin_marker, end_marker) && source.match(pattern)[0] == expected
    end

    def plural(count, noun)
      "#{count} #{noun}#{count == 1 ? '' : 's'}"
    end

    def hex(value, width)
      value.to_s(16).rjust(width, "0")
    end

    def runs(values)
      values.sort.uniq.slice_when { |left, right| right != left + 1 }.to_a
    end

    def hex_runs(values, width, prefix: nil, code: true)
      runs(values).map do |run|
        first = "0x#{hex(run.first, width)}"
        last = "0x#{hex(run.last, width)}"
        value = run.length == 1 ? first : "#{first}..#{last}"
        value = "#{prefix}=#{value}" if prefix
        code ? "`#{value}`" : value
      end.join(", ")
    end

    def allocation_summary
      sentences = []
      r3_used = @instruction_set.entries.select { |entry| entry[:format] == "R3" }
                                .map { |entry| entry[:funct7] }
      sentences << "R3 uses #{hex_runs(r3_used, 2, prefix: 'funct7')}; " \
                   "#{hex_runs(@instruction_set.r3_reserved_funct7, 2)} are reserved."

      @instruction_set.banks.each do |bank|
        width = [(bank[:selector_bits] + 3) / 4, 1].max
        used = @instruction_set.used_selectors(bank)
        fixed_members = @instruction_set.fixed_members.select { |member| member[:bank] == bank[:id] }
        unused_reserved = bank[:reserved_selectors] - fixed_members.map { |member| member[:selector] }
        free = @instruction_set.free_selectors(bank)
        clauses = []
        clauses << "uses #{hex_runs(used, width, prefix: bank[:selector_name])}" unless used.empty?
        fixed_members.each do |member|
          clauses << "fixes `#{member[:name]}` at `#{bank[:selector_name]}=0x#{hex(member[:selector], width)}`"
        end
        clauses << "reserves #{hex_runs(unused_reserved, width)}" unless unused_reserved.empty?
        if free.empty?
          clauses << "has no free selectors"
        else
          clauses << "leaves #{hex_runs(free, width)} " \
                     "(#{plural(free.length, 'selector')}) free"
        end
        sentences << "#{bank[:label]} (`funct7=0x#{hex(bank[:funct7], 2)}`) #{clauses.join('; ')}."
      end

      free = @instruction_set.free_funct7
      sentences << "The #{plural(free.length, '`funct7` value')} #{hex_runs(free, 2)} remain free."
      sentences.join(" ")
    end

    def bit_range(field)
      field[:hi] == field[:lo] ? field[:hi].to_s : "#{field[:hi]}:#{field[:lo]}"
    end

    def render_fixed_field(field)
      digits = [(field[:width] + 3) / 4, 1].max
      rendered = "`[#{bit_range(field)}]=0x#{hex(field[:value], digits)}`"
      field[:attribute] ? "#{rendered} (`#{field[:attribute]}`)" : rendered
    end

    def escape(text)
      text.to_s.gsub("|", "\\|")
    end
  end
end
