#!/usr/bin/env ruby
# frozen_string_literal: true

root = File.expand_path("..", __dir__)
allocations_path = File.join(root, "src", "instruction-encoding-allocations.adoc")
instructions_path = File.join(root, "src", "instructions.adoc")
output_path = File.join(root, "INSTRUCTION_ENCODINGS.md")

attributes = {}
File.foreach(allocations_path) do |line|
  match = line.match(/^:([a-z0-9-]+):\s+(\S+)$/)
  attributes[match[1]] = match[2] if match
end

entries = []
File.read(instructions_path).scan(/^=== `([^`]+)`\n(.*?)(?=^=== `|\z)/m) do |name, section|
  diagram = section.lines.find { |line| line.start_with?('{"reg":') }
  abort "#{name} has no WaveDrom encoding" unless diagram

  mnemonic = section[/Mnemonic::\n`([^`]+)`/, 1]
  abort "#{name} has no mnemonic" unless mnemonic

  position = 0
  mask = 0
  match_value = 0
  fields = []

  diagram.scan(/"bits":(\d+),"name":\s*(\{[^}]+\}|"[^"]+"|0x[0-9a-f]+|\d+)/) do |width_text, token|
    width = width_text.to_i
    lo = position
    hi = position + width - 1

    if token.start_with?('"')
      fields << { kind: :operand, name: token[1...-1], width: width, hi: hi, lo: lo }
    else
      attribute = token[/\A\{([^}]+)\}\z/, 1]
      value_text = attribute ? attributes.fetch(attribute) : token
      value = value_text.start_with?("0x") ? value_text.to_i(16) : value_text.to_i
      abort "#{name} value #{value_text} does not fit bits #{hi}:#{lo}" if value >= (1 << width)

      field_mask = ((1 << width) - 1) << lo
      mask |= field_mask
      match_value |= value << lo
      fields << { kind: :fixed, value: value, attribute: attribute, width: width, hi: hi, lo: lo }
    end
    position += width
  end

  abort "#{name} encoding is #{position} bits, expected 32" unless position == 32
  entries << { name: name, mnemonic: mnemonic, fields: fields, mask: mask, value: match_value }
end

overlaps = entries.combination(2).select do |left, right|
  common_mask = left[:mask] & right[:mask]
  ((left[:value] ^ right[:value]) & common_mask).zero?
end
exact_duplicates, partial_overlaps = overlaps.partition do |left, right|
  left[:mask] == right[:mask] && left[:value] == right[:value]
end

range = lambda do |field|
  field[:hi] == field[:lo] ? field[:hi].to_s : "#{field[:hi]}:#{field[:lo]}"
end

hex_field = lambda do |field|
  digits = [(field[:width] + 3) / 4, 1].max
  rendered = "`[#{range.call(field)}]=0x#{field[:value].to_s(16).rjust(digits, '0')}`"
  field[:attribute] ? "#{rendered} (`#{field[:attribute]}`)" : rendered
end

escape = ->(text) { text.to_s.gsub("|", "\\|") }

lines = []
lines << "# AME instruction encoding table"
lines << ""
lines << "> Generated by `ruby scripts/generate-instruction-encoding-table.rb` from " \
         "`src/instructions.adoc` and `src/instruction-encoding-allocations.adoc`. Do not edit manually."
lines << ""
lines << "The canonical decoder test is `(instruction_word & mask) == match`. " \
         "Fixed fields are listed from most-significant to least-significant bits."
lines << ""
lines << "## Collision audit"
lines << ""
lines << "| Check | Count |"
lines << "|---|---:|"
lines << "| Instructions | #{entries.length} |"
lines << "| Exact duplicate decode patterns | #{exact_duplicates.length} |"
lines << "| Partial decode-space overlaps | #{partial_overlaps.length} |"

unless overlaps.empty?
  lines << ""
  lines << "| Type | Instruction A | Instruction B |"
  lines << "|---|---|---|"
  exact_duplicates.each { |a, b| lines << "| Exact duplicate | `#{a[:name]}` | `#{b[:name]}` |" }
  partial_overlaps.each { |a, b| lines << "| Partial overlap | `#{a[:name]}` | `#{b[:name]}` |" }
end

lines << ""
lines << "## Resolved conflicts found by this audit"
lines << ""
lines << "The original `funct7=0x00` through `0x07` assignments for the accumulator-format " \
         "matrix-multiply family partially overlapped the scalar `.ew.x` decode space. " \
         "The same 32-bit word selected both instructions when `md` was 0, 2, 4, or 6. " \
         "They now use the verified-free contiguous range `0x1b` through `0x22`."
lines << ""
lines << "| Accumulator instruction | Old `funct7` | Conflicting scalar instruction | New `funct7` |"
lines << "|---|---:|---|---:|"
[
  ["mmul.2d", 0x00, "madd.ew.x", 0x1b],
  ["mmulacc.2d", 0x01, "msub.ew.x", 0x1c],
  ["mmulneg.2d", 0x02, "mmin.ew.x", 0x1d],
  ["mmulaccneg.2d", 0x03, "mmax.ew.x", 0x1e],
  ["mmulat.2d", 0x04, "mmean.ew.x", 0x1f],
  ["mmulatacc.2d", 0x05, "mabsdiff.ew.x", 0x20],
  ["mmulbt.2d", 0x06, "mhdiff.ew.x", 0x21],
  ["mmulbtacc.2d", 0x07, "mand.ew.x", 0x22]
].each do |accumulator, old_funct7, scalar, new_funct7|
  lines << format("| `%s` | `0x%02x` | `%s` | `0x%02x` |", accumulator, old_funct7, scalar, new_funct7)
end

lines << ""
lines << "## All instruction encodings"
lines << ""
lines << "| # | Instruction | Mnemonic | Operand fields | Function/fixed fields | Mask | Match |"
lines << "|---:|---|---|---|---|---|---|"

entries.each_with_index do |entry, index|
  operands = entry[:fields].select { |field| field[:kind] == :operand }
                          .sort_by { |field| -field[:hi] }
                          .map { |field| "`#{field[:name]}[#{range.call(field)}]`" }
                          .join("; ")
  fixed = entry[:fields].select { |field| field[:kind] == :fixed }
                       .sort_by { |field| -field[:hi] }
                       .map { |field| hex_field.call(field) }
                       .join("; ")
  lines << format(
    "| %d | `%s` | `%s` | %s | %s | `0x%08x` | `0x%08x` |",
    index + 1,
    escape.call(entry[:name]),
    escape.call(entry[:mnemonic]),
    operands,
    fixed,
    entry[:mask],
    entry[:value]
  )
end

generated = "#{lines.join("\n")}\n"
if ARGV == ["--check"]
  current = File.exist?(output_path) ? File.read(output_path) : ""
  abort "INSTRUCTION_ENCODINGS.md is stale; run ruby scripts/generate-instruction-encoding-table.rb" unless current == generated

  puts "checked instruction encoding table: #{entries.length} entries are current"
elsif ARGV.empty?
  File.write(output_path, generated)
  puts "wrote #{output_path} with #{entries.length} instruction encodings"
else
  abort "usage: #{$PROGRAM_NAME} [--check]"
end
