[[intro]]
== Introduction

The Attached Matrix Extension (AME) adds instructions to accelerate tensor codes at the heart of many machine learning and HPC applications. It has the following goals:

Scalable::
*  AME targets markets ranging from low-power embedded edge to datacenter and HPC.
*  Due to the extreme range of target designs, some AME implementation parameters affect binary compatibility. Thus, code compiled for one AME implementation may not run another, though profiles are expected to constrain parameters so that binaries are compatible within a market.

Isolated::
*  AME is designed to work well on tensor codes regardless of whether the host hart implements RISC-V Vector (RVV). Implementing RVV is not a prerequisite of AME. Frequently moving state between RVV and AME may degrade performance on some implementations.

Detachable::
*  AME allows harts to share an AME backend and provides explicit ownership
   management; see <<shared-ame-backend>>. Implementations may instead provide
   dedicated backends.
